### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by 6952350** [JuchiaLu/luci-app-mnnu#1]
同学你好，我用的是x-wrt装完这个ipk之后填账号密码后不会执行

**Comment by JuchiaLu** [comment]
> 同学你好，我用的是x-wrt装完这个ipk之后填账号密码后不会执行

这个软件只有在 OpenMptcpRouter 下能用，openwrt 下是不能直接用的，还缺少很多依赖。

**Comment by 6952350** [comment]
> > 同学你好，我用的是x-wrt装完这个ipk之后填账号密码后不会执行
> 
> 这个软件只有在 OpenMptcpRouter 下能用，openwrt 下是不能直接用的，还缺少很多依赖。

谢谢，那准备买软路由去了

**Comment by JuchiaLu** [comment]
> > > 同学你好，我用的是x-wrt装完这个ipk之后填账号密码后不会执行
> > 
> > 
> > 这个软件只有在 OpenMptcpRouter 下能用，openwrt 下是不能直接用的，还缺少很多依赖。
> 
> 谢谢，那准备买软路由去了

可以先在虚拟机下试试，能用了再考虑。还有就是学校校园网居然还没修好

**Comment by 6952350** [comment]
> > > > 同学你好，我用的是x-wrt装完这个ipk之后填账号密码后不会执行
> > > 
> > > 
> > > 这个软件只有在 OpenMptcpRouter 下能用，openwrt 下是不能直接用的，还缺少很多依赖。
> > 
> > 
> > 谢谢，那准备买软路由去了
> 
> 可以先在虚拟机下试试，能用了再考虑。还有就是学校校园网居然还没修好

大一学生还有四年要熬，本来想用openwrt多拨mentohust实现的，但是openwrt上的mentohust死活认证不成功，只有老毛子成功了，不过只能单拨

**Comment by 6952350** [comment]
还有个问题，这个需要我购买vps服务器吗😂
